spring.application.name=moviestreaming

# --------- CẤU HÌNH MONGODB ---------
# Kết nối MongoDB Local
spring.data.mongodb.uri=mongodb://localhost:27017/moviestreamingdb

# TMDB API (The Movie Database)
tmdb.api.key=7e53636ceb00490e8cf14bef210310e7
tmdb.api.base=https://api.themoviedb.org/3
tmdb.image.base=https://image.tmdb.org/t/p/w500

# JWT Configuration
# Secret key >= 256 bit (32 ký tự) để ký HS256
jwt.secret=LiqiPhimSecretKey2026!VeryLongAndSecure#ForHS256
# Thời gian hết hạn token: 7 ngày (ms)
jwt.expiration-ms=604800000
