spring.application.name=moviestreaming

# Cấu hình H2 file-based ổn định (không phụ thuộc thư mục chạy app)
# DB sẽ nằm trong: C:\Users\<user>\.moviestreaming\moviestreamingdb.*
spring.datasource.url=jdbc:h2:file:${user.home}/.moviestreaming/moviestreamingdb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
